version: "3"
services:
  metawebanalyzeapp:
    image: webapp
    environment:
      - host_name=www.facebook.com
    volumes:
      - ./log:/app/log
  googlewebanalyzeapp:
    image: webapp
    environment:
      - host_name=www.google.com
    volumes:
      - ./log:/app/log
  netflixwebanalyzeapp:
    image: webapp
    environment:
      - host_name=www.netflix.com
    volumes:
      - ./log:/app/log  
  applewebanalyzeapp:
    image: webapp
    environment:
      - host_name=www.apple.com
    volumes:
      - ./log:/app/log
  amazonwebanalyzeapp:
    image: webapp
    environment:
      - host_name=www.amazon.com
    volumes:
      - ./log:/app/log  